name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pull repo
      - name: Pull repo
        uses: actions/checkout@v4
      
      # Build Docker image
      - name: Build Docker image
        run: |
         docker build -t my-app:latest .
        
      # Print hello
      - name: Print hello
        run: echo "Hello"
        